### ISSUE TITLE
Link blocked

### ISSUE THREAD

**Issue by IcyonGit** [Bored-Entertainment/themesacomplex#11]
The link is blocked
![Screenshot 2022-04-13 12 47 51 PM](https://user-images.githubusercontent.com/100136502/163230626-85f974b6-8e90-4ff6-8213-af40a13e2c5b.png)

**Comment by amhooman** [comment]
ummmmmmm............................ your tech support in your school probably blocked it. Sorry. We can't talk to your school about it.

**Comment by greymesa** [comment]
Good afternoon. 
We are currently working on hosting the website on more domains, I will keep this issue locked until we do add more.

**Comment by PiSaucer** [comment]
What do you want me to do?

**Comment by greymesa** [comment]
mb, are you the one who added vercel?

**Comment by PiSaucer** [comment]
No, that wasn't me

**Comment by greymesa** [comment]
ah alright

**Comment by greymesa** [comment]
can you remove it? i'm pretty sure slasher added it without telling us

**Comment by amhooman** [comment]
what is vercel?

**Comment by The-Ducks-Code** [comment]
dead site lol
