### ISSUE TITLE
Help with fork

### ISSUE THREAD

**Issue by IcyonGit** [Bored-Entertainment/themesacomplex#12]
If I fork this repo and make a Github page website with it would it work or not? If it does work, do I have permission?

**Comment by amhooman** [comment]
I'm not fully sure it would completely work, but as long as you give permission, and leave a link to our website, I think it's fine. Don't do it yet, but I'll ask the other devs on the discord serber

**Comment by greymesa** [comment]
> I'm not fully sure it would completely work, but as long as you give permission, and leave a link to our website, I think it's fine. Don't do it yet, but I'll ask the other devs on the discord server

slash, don’t respond to issues if you don’t know the proper response.

**Comment by greymesa** [comment]
> I'm not fully sure it would completely work, but as long as you give permission, and leave a link to our website, I think it's fine. Don't do it yet, but I'll ask the other devs on the discord server


slash, do not, under ANY CIRCUMSTANCES respond to issues if you don't know the proper response.

**Comment by greymesa** [comment]
> If I fork this repo and make a Github page website with it would it work or not? If it does work, do I have permission?


check the license for usage info, site should work on github pages.

**Comment by amhooman** [comment]
> slash, do not, under ANY CIRCUMSTANCES respond to issues if you don't know the proper response.

Sorry about that...
