### ISSUE TITLE
Lambda icon does not appear (except on homepage)

### ISSUE THREAD

**Issue by CycloKid** [Bored-Entertainment/themesacomplex#32]
This is happening because the page is attempting to access the file from the wrong url.
For example, the emulator subpage attempts to grab it from:
[https://bored-entertainment.github.io/themesacomplex/emulators/images/lambda.png](https://bored-entertainment.github.io/themesacomplex/emulators/images/lambda.png)
When it should be grabbing it from:
[https://bored-entertainment.github.io/themesacomplex/images/lambda.png](https://bored-entertainment.github.io/themesacomplex/images/lambda.png)

This is easily fixed by hardcoding the url, or adding `../` at the start of the url, adding more dots depending on how many directories it is below. I may be wrong since its been a while since ive touched html.

**Comment by The-Ducks-Code** [comment]
thanks for the concern but this is a dead site, I am not sure why we havent archived it.
